automation:
  - alias: "heater dh minus 10"
    initial_state: True
    trigger:
     - platform: time_pattern
       minutes: '/5'
       seconds: 2
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'binary_sensor.workday_sensor'
          state: 'on'   
        - condition: numeric_state
          entity_id: sensor.dark_sky_temperature
          below: -10
        - condition: template
          value_template: '{{ ((now().strftime("%s") | int + 3600) | timestamp_custom("%H:%M")) == states.sensor.departuretime_dh.state  }}'
    action:
       - service: script.turn_on
         entity_id: script.heater_dh_on
       - service: notify.pushbullet
         data_template:
           message: 'Motorvärmare (-10°) är på i 1h från {{now().strftime("%H:%M:%S")}} Temp ute: {{ states.sensor.dark_sky_temperature.state}}°C'
       - service: homeassistant.turn_off
         entity_id: automation.heater_dh_minus_10, automation.heater_dh_minus_3, automation.heater_dh_plus_3
   
  - alias: "heater dh minus 3"
    initial_state: True
    trigger:
     - platform: time_pattern
       minutes: '/5'
       seconds: 2
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'binary_sensor.workday_sensor'
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.dark_sky_temperature
          below: -3.0 
        - condition: template
          value_template: '{{ ((now().strftime("%s") | int + 2700) | timestamp_custom("%H:%M")) == states.sensor.departuretime_dh.state  }}'       
    action:
       - service: script.turn_on
         entity_id: script.heater_dh_on
       - service: notify.pushbullet
         data_template:
           message: 'Motorvärmare (-3°) är på i 45m från {{now().strftime("%H:%M:%S")}} Temp ute: {{ states.sensor.dark_sky_temperature.state}}°C'
       - service: homeassistant.turn_off
         entity_id: automation.heater_dh_plus_3, automation.heater_dh_minus_3, automation.heater_dh_minus_10
   
  - alias: "heater dh plus 3"
    initial_state: True
    trigger:
     - platform: time_pattern
       minutes: '/5'
       seconds: 2
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'binary_sensor.workday_sensor'
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.dark_sky_temperature
          below: 3.0 
        - condition: template
          value_template: '{{ ((now().strftime("%s") | int + 1800) | timestamp_custom("%H:%M")) == states.sensor.departuretime_dh.state  }}'       
    action:
       - service: script.turn_on
         entity_id: script.heater_dh_on
       - service: notify.pushbullet
         data_template:
           message: 'Motorvärmare (+3°) är på i 30 min från {{now().strftime("%H:%M:%S")}} Temp ute: {{ states.sensor.dark_sky_temperature.state}}°C'
       - service: homeassistant.turn_off
         entity_id: automation.heater_dh_plus_3, automation.heater_dh_minus_3, automation.heater_dh_minus_10
 
  - alias: "heater dh enabled"
    trigger:
     - platform: time
       at: '00:05:00'
    condition:
     - condition: state
       entity_id: 'binary_sensor.workday_sensor'
       state: 'on'  
    action:
      - service: homeassistant.turn_on
        entity_id:
          - automation.heater_dh_minus_10
          - automation.heater_dh_minus_3
          - automation.heater_dh_plus_3
 
  - alias: "heater dh off"
    initial_state: False
    trigger:
     - platform: time_pattern
       minutes: '/5'
       seconds: 2
    condition:
      - condition: template
        value_template: '{{ now().hour == (states.input_number.heater_dh_hour.state  | round(0))  and  now().minute == (states.input_number.heater_dh_minutes.state  | round(0) )  }}'       
    action:
       - service: homeassistant.turn_off
         entity_id: switch.maz704_heater, automation.heater_dh_off
       - service: notify.pushbullet
         data_template:
           message: 'Motorvärmare Stängs nu av {{now().strftime("%H:%M:%S")}} Temp ute: {{ states.sensor.dark_sky_temperature.state}}°C'

# Sensor section
sensor:
  - platform: template
    sensors:
      departuretime_dh:
        friendly_name: 'Avresetid'
        value_template: '{% if states.input_number.heater_dh_hour.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_number.heater_dh_hour.state|round(0)|string }}:{% if states.input_number.heater_dh_minutes.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_number.heater_dh_minutes.state|round(0)|string }}'
        entity_id: 
         - input_number.heater_dh_minutes
         - input_number.heater_dh_hour
 
# Input section
input_number:
  heater_dh_hour:
    name: Timmar
    icon: mdi:timer
    initial: 07
    min: 0
    max: 23
    step: 1
   
  heater_dh_minutes:
    name: Minuter
    icon: mdi:timer
    initial: 20
    min: 0
    max: 55
    step: 5
    
# Script section
script:
    heater_dh_on:
     sequence:
       - service: homeassistant.turn_on 
         entity_id: switch.XXXXXX_heater
       - service: automation.turn_on
         entity_id: automation.heater_dh_off

#Workday Sensor
binary_sensor:
  - platform: workday
    country: SE
    workdays: [mon, tue, wed, thu, fri]
